# package querytest
query.sql:4:22: column "invalid_reference" does not exist
